# image: https://hub.docker.com/r/tensorflow/tensorflow
# docs: https://github.com/tensorflow/tensorflow

version: '3.8'

services:
  tensorflow:
    image: tensorflow/tensorflow:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_PORT}:8888'
      - '${APP_GUI_PORT}:6006'
    volumes:
      - tensorflow:/tf/notebooks

networks:
  default:
      name: ${APP_NAME}

volumes:
  tensorflow:
